run:
  allow-parallel-runners: true
  tests: false
  skip-dirs:
    - bin
issues:
  fix: true

output:
  format: colored-line-number
  print-linter-name: true
  print-issued-lines: true


linters:
  enable-all: true
  disable:
    - forbidigo
    - exhaustivestruct
    - gofmt
    - noctx