security:
  token: MzY5MTgxMjYzMzUwNzI2NjU3.YDp5FQ.c1peadVEFyyNdo1q4Tm3JC-SFic
  x_super_properties: 'eyJvcyI6Ik1hYyBPUyBYIiwiYnJvd3NlciI6IkNocm9tZSIsImRldmljZSI6IiIsInN5c3RlbV9sb2NhbGUiOiJydS1SVSIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDExXzJfMSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzg4LjAuNDMyNC4xOTIgU2FmYXJpLzUzNy4zNiIsImJyb3dzZXJfdmVyc2lvbiI6Ijg4LjAuNDMyNC4xOTIiLCJvc192ZXJzaW9uIjoiMTEuMi4xIiwicmVmZXJyZXIiOiJodHRwczovL2R1Y2tkdWNrZ28uY29tLyIsInJlZmVycmluZ19kb21haW4iOiJkdWNrZHVja2dvLmNvbSIsInNlYXJjaF9lbmdpbmUiOiJkdWNrZHVja2dvIiwicmVmZXJyZXJfY3VycmVudCI6IiIsInJlZmVycmluZ19kb21haW5fY3VycmVudCI6IiIsInJlbGVhc2VfY2hhbm5lbCI6InN0YWJsZSIsImNsaWVudF9idWlsZF9udW1iZXIiOjc3OTYyLCJjbGllbnRfZXZlbnRfc291cmNlIjpudWxsfQ=='
  user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36'
  sec_ch_ua: '"Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"'

message:
    text: "@Костя#1624 ???"
    server_id: 426485886390108161
    channel_id: 727931852605882400

settings:
  min_rand_minute: 2
  max_rand_minute: 10

planned:
  - 11
  - 14
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 00
  - 01
  - 02

debug: false